# Generated by Django 5.0.7 on 2024-08-12 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopservice_app', '0003_alter_feedback_feedback_sellerfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('status', models.BooleanField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='laptopservice_app.seller')),
            ],
        ),
    ]
