# Generated by Django 5.0.7 on 2024-08-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopservice_app', '0005_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='document',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
