# Generated by Django 5.0.7 on 2024-08-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopservice_app', '0010_buynow_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buynow',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buynow',
            name='post',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
