# Generated by Django 5.0.7 on 2024-08-23 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopservice_app', '0012_alter_buynow_phone_alter_buynow_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.IntegerField(max_length=16)),
                ('cvv', models.IntegerField(max_length=3)),
                ('expiry_date', models.DateField(auto_now=True)),
                ('buynowProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buynow', to='laptopservice_app.buynow')),
            ],
        ),
    ]
