# Generated by Django 5.0.7 on 2024-08-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopservice_app', '0013_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardnumber',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.CharField(max_length=5),
        ),
    ]
