# Generated by Django 5.0.7 on 2024-08-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopservice_app', '0014_alter_payment_cardnumber_alter_payment_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardnumber',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.CharField(max_length=7),
        ),
    ]
